// Generated by CoffeeScript 1.4.0
(function() {
  var PORT, app, express, pay_stripe;

  express = require("express");

  app = express.createServer();

  app.use(express["static"](__dirname + "/public"));

  app.use(express.bodyParser());

  app.use(app.router);

  pay_stripe = require("./pay_stripe.js");

  app.use(express.bodyParser());

  app.get("/", function(req, res) {
    return res.render("index.ejs", {
      title: "The Grid"
    });
  });

  app.get("/plans", function(req, res) {
    return res.render("plans.ejs", {
      title: "The Grid"
    });
  });

  app.get("/order_basic", function(req, res) {
    return res.render("order_basic.ejs", {
      title: "Support the Grid",
      amount: 20
    });
  });

  app.post("/order_basic", pay_stripe.process_payment_basic);

  app.get("/plans_pro", function(req, res) {
    return res.render("plans_pro.ejs", {
      title: "Pro Package"
    });
  });

  app.post("/plans_pro", pay_stripe.process_payment_pro);

  app.get("/plans_developer", function(req, res) {
    return res.render("plans_developer.ejs", {
      title: "Developer Package"
    });
  });

  app.post("/plans_developer", pay_stripe.process_payment_developer);

  app.get("/*", function(req, res) {
    return res.status(404).render("error.ejs", {
      title: "Error"
    });
  });

  PORT = 3000;

  app.listen(PORT, function() {
    return console.log("Listening on " + PORT);
  });

}).call(this);
