// Generated by CoffeeScript 1.4.0
(function() {
  var noflo;

  noflo = require('noflo');

  exports.getPaymentGraph = function(apiKey, chargeCb, errorCb) {
    var graph;
    graph = new noflo.Graph('ProcessPayment');
    graph.addNode('Process', 'node-stripe/ProcessPayment');
    graph.addNode('Charge', 'Callback');
    graph.addNode('Error', 'Callback');
    graph.addEdge('Process', 'charge', 'Charge', 'in');
    graph.addEdge('Process', 'error', 'Error', 'in');
    graph.addInitial(apiKey, 'Process', 'apikey');
    graph.addInitial(chargeCb, 'Charge', 'callback');
    graph.addInitial(errorCb, 'Error', 'callback');
    return graph;
  };

  exports.processPayment = function(apiKey, charge, customer, callback) {
    var graph;
    graph = exports.getPaymentGraph(apiKey, function(charge) {
      return callback(null, charge);
    }, function(error) {
      return callback(error, null);
    });
    graph.addInitial(charge, 'Process', 'chargedata');
    graph.addInitial(customer, 'Process', 'customerdata');
    return noflo.createNetwork(graph, function(network) {
      /*
          network.on 'data', (data) ->
            console.log data
          network.on 'start', (start) ->
            console.log start
          network.on 'end', (end) ->
            console.log end
      */

    });
  };

}).call(this);
