// Generated by CoffeeScript 1.3.3
(function() {

  exports.process_payment_basic = function(req, res) {
    var api_key, stripe, token, _ref;
    console.log("Basic Account Initiated");
    api_key = 'sk_test_ixWCFyk1Jl9Rt6TtLMkzg3Qd';
    stripe = require('stripe')(api_key);
    token = req != null ? (_ref = req.body) != null ? _ref.stripeToken : void 0 : void 0;
    if (!token) {
      console.log("token not found");
    }
    return stripe.charges.create({
      amount: 2000,
      currency: "usd",
      card: token,
      description: "svetly@example.com"
    });
  };

  exports.process_payment_pro = function(req, res) {
    var api_key, stripe, token, _ref;
    console.log("Pro Account Initiated");
    api_key = 'sk_test_ixWCFyk1Jl9Rt6TtLMkzg3Qd';
    stripe = require('stripe')(api_key);
    token = req != null ? (_ref = req.body) != null ? _ref.stripeToken : void 0 : void 0;
    if (!token) {
      console.log("token not found");
    }
    return stripe.customers.create({
      card: req.body.stripeToken,
      email: "daniel@gmail.com",
      plan: "plans_pro"
    }, function(err, customer) {
      var id, msg;
      if (err) {
        msg = customer.error.message || "unknown";
        return res.send("Error while processing your payment " + msg);
      } else {
        id = customer.id;
        console.log("Success! Customer with Stripe ID " + id + " just signed up!");
        return res.send('ok');
      }
    });
  };

  exports.process_payment_developer = function(req, res) {
    var api_key, stripe, token, _ref;
    api_key = 'sk_test_ixWCFyk1Jl9Rt6TtLMkzg3Qd';
    stripe = require('stripe')(api_key);
    token = req != null ? (_ref = req.body) != null ? _ref.stripeToken : void 0 : void 0;
    if (!token) {
      console.log("token not found");
    }
    return stripe.customers.create({
      card: req.body.stripeToken,
      email: "developer@example.com",
      plan: "plans_developer"
    }, function(err, customer) {
      var id, msg;
      if (err) {
        msg = customer.error.message || "unknown";
        return res.send("Error while processing your payment " + msg);
      } else {
        id = customer.id;
        console.log("Success! Customer with Stripe ID " + id + " just signed up!");
        return res.send('ok');
      }
    });
  };

}).call(this);
